In [30]:
# 라이브러리 불러오기
import pandas as pd

# 데이터 불러오기
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_2/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_2/test.csv")

In [31]:
train.head(), test.head()

(       ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
 0  462809    Male           No   22        No  Healthcare              1.0
 1  466315  Female          Yes   67       Yes    Engineer              1.0
 2  461735    Male          Yes   67       Yes      Lawyer              0.0
 3  461319    Male          Yes   56        No      Artist              0.0
 4  460156    Male           No   32       Yes  Healthcare              1.0

   Spending_Score  Family_Size  Var_1  Segmentation
 0            Low          4.0  Cat_4             4
 1            Low          1.0  Cat_6             2
 2           High          2.0  Cat_6             2
 3        Average          2.0  Cat_6             3
 4            Low          3.0  Cat_6             3  ,
        ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
 0  458989  Female          Yes   36       Yes    Engineer              0.0
 1  458994    Male          Yes   37       Yes  Healthcare              8.0
 2  459000    Male          Yes   59        No   Executive             11.0
 3  459003    Male          Yes   47       Yes      Doctor              0.0
 4  459005    Male          Yes   61       Yes      Doctor              5.0

   Spending_Score  Family_Size  Var_1
 0            Low          1.0  Cat_6
 1        Average          4.0  Cat_6
 2           High          2.0  Cat_6
 3           High          5.0  Cat_4
 4            Low          3.0  Cat_6  )

In [32]:
train.info(), test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6665 entries, 0 to 6664
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               6665 non-null   int64
 1   Gender           6665 non-null   object
 2   Ever_Married     6665 non-null   object
 3   Age              6665 non-null   int64
 4   Graduated        6665 non-null   object
 5   Profession       6665 non-null   object
 6   Work_Experience  6665 non-null   float64
 7   Spending_Score   6665 non-null   object
 8   Family_Size      6665 non-null   float64
 9   Var_1            6665 non-null   object
 10  Segmentation     6665 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 572.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2154 entries, 0 to 2153
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               2154 non-null   int64
 1   Gender           2154 non-null   object
 2   Ever_Married     2154 non-null   object
 3   Age              2154 non-null   int64
 4   Graduated        2154 non-null   object
 5   Profession       2154 non-null   object
 6   Work_Experience  2154 non-null   float64
 7   Spending_Score   2154 non-null   object
 8   Family_Size      2154 non-null   float64
 9   Var_1            2154 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 168.4+ KB

(None, None)

In [33]:
train.shape, test.shape

((6665, 11), (2154, 10))

In [34]:
target = train.pop("Segmentation");

In [35]:
# from sklearn.preprocessing import LabelEncoder

# cols = train.select_dtypes(include='O').columns
# for col in cols:
#     le = LabelEncoder()
#     train[col] = le.fit_transform(train[col])
#     test[col] = le.transform(test[col])

In [36]:
train = pd.get_dummies(train)
test = pd.get_dummies(test)

In [37]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=0)
model.fit(train, target)
pred = model.predict(test)

In [38]:
test_id = test.copy()['ID']
test_id

0       458989
1       458994
2       459000
3       459003
4       459005
         ...
2149    467950
2150    467954
2151    467958
2152    467961
2153    467968
Name: ID, Length: 2154, dtype: int64

In [39]:
submit = pd.DataFrame({'ID':test_id, 'Segmentation':pred}).to_csv("submitsion.csv", index=False)

In [40]:
pd.read_csv("submitsion.csv")

          ID  Segmentation
0     458989             2
1     458994             3
2     459000             3
3     459003             3
4     459005             2
...      ...           ...
2149  467950             4
2150  467954             4
2151  467958             2
2152  467961             2
2153  467968             4

[2154 rows x 2 columns]